# Generated by Django 5.2.3 on 2025-07-22 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0002_registrosesion_verificacioncorreo'),
    ]

    operations = [
        migrations.AddField(
            model_name='emocion',
            name='valor',
            field=models.IntegerField(default=0),
        ),
    ]
