# Generated by Django 5.2.3 on 2025-07-22 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0004_alter_emocion_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emocion',
            name='valor',
            field=models.IntegerField(default=0),
        ),
    ]
