# Generated by Django 5.2.3 on 2025-07-22 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0005_alter_emocion_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emocion',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
